//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSR_MAGALU_BUSINESS.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSR_MAGALU_BUSINESS.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cliente {0} foi criado com sucesso !.
        /// </summary>
        public static string ClienteCadastradoSucesso {
            get {
                return ResourceManager.GetString("ClienteCadastradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cliente {0} foi editado com sucesso !.
        /// </summary>
        public static string ClienteEditadoSucesso {
            get {
                return ResourceManager.GetString("ClienteEditadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este CPF/CNPJ já está cadastrado para outro Cliente !.
        /// </summary>
        public static string DocumentoJaUtilizado {
            get {
                return ResourceManager.GetString("DocumentoJaUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O documento {0} não está cadastrado, pode utilizar !.
        /// </summary>
        public static string DocumentoNaoCadastrado {
            get {
                return ResourceManager.GetString("DocumentoNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar um cpf ou cpnj valido para realizar a validação !.
        /// </summary>
        public static string DocumentoNaoInformado {
            get {
                return ResourceManager.GetString("DocumentoNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O documento {0} informado, não é valido !.
        /// </summary>
        public static string DocumentoNaoValido {
            get {
                return ResourceManager.GetString("DocumentoNaoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este e-mail já está cadastrado para outro Cliente !.
        /// </summary>
        public static string EmailJaUtilizado {
            get {
                return ResourceManager.GetString("EmailJaUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail {0} não está cadastrado, pode utilizar !.
        /// </summary>
        public static string EmailNaoCadastrado {
            get {
                return ResourceManager.GetString("EmailNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar um e-mail valido para realizar a validação !.
        /// </summary>
        public static string EmailNaoInformado {
            get {
                return ResourceManager.GetString("EmailNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail {0} informado, não é valido !.
        /// </summary>
        public static string EmailNaoValido {
            get {
                return ResourceManager.GetString("EmailNaoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um erro inesperado aconteceu, tente novamente !.
        /// </summary>
        public static string ErroInesperado {
            get {
                return ResourceManager.GetString("ErroInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta Inscrição Estadual já está cadastrada para outro Cliente !.
        /// </summary>
        public static string InscricaoEstadualJaUtilizada {
            get {
                return ResourceManager.GetString("InscricaoEstadualJaUtilizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário informar um inscrição estadual valida para realizar a validação !.
        /// </summary>
        public static string InscricaoEstadualNaoInformada {
            get {
                return ResourceManager.GetString("InscricaoEstadualNaoInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A inscrição estadual {0} não está cadastrada, pode utilizar !.
        /// </summary>
        public static string InscricaoNaoCadastrada {
            get {
                return ResourceManager.GetString("InscricaoNaoCadastrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solicitação inválida, tente novamente !.
        /// </summary>
        public static string ModelStateInvalido {
            get {
                return ResourceManager.GetString("ModelStateInvalido", resourceCulture);
            }
        }
    }
}
